### ISSUE TITLE
dateTimeFormatter is ignored on blur event

### ISSUE THREAD

**Issue by rdourado** [abadi199/datetimepicker#10]
I am trying to set up dateTimeFormatter like this (using [mgold/elm-date-format](http://package.elm-lang.org/packages/mgold/elm-date-format/1.2.0/Date-Format) package):

```elm
dateTimeFormatter : Date -> String
dateTimeFormatter date =
    Date.Format.format "%d/%m/%Y %I:%M %p" date
```

It works when I select a date:

![screen shot 2017-02-20 at 17 45 24](https://cloud.githubusercontent.com/assets/44909/23141399/6b735678-f795-11e6-9e51-baed942ca3b1.png)

But it seems to stop working when the input loses focus (in this case, month and day are changing position):

![screen shot 2017-02-20 at 17 45 51](https://cloud.githubusercontent.com/assets/44909/23141424/83d48728-f795-11e6-83d5-df3df4af426f.png)

**Comment by rdourado** [comment]
It was a problem with my code. Sorry.

**Comment by rdourado** [comment]
It looks like the problem is with this line: https://github.com/abadi199/datetimepicker/blob/master/src/DateTimePicker/Events.elm#L26

**Comment by rdourado** [comment]
If someone is looking for a quick solution, that's my workaround:

```elm
DateChange state selectedDate ->
    let
        formatDate str date =
            Date.Format.format str <| 
                Maybe.withDefault model.today date

        oldDate = 
            model.selectedDate

        newDate =
            if selectedDate == Nothing then
                oldDate
            else if formatDate "%m/%d" selectedDate == formatDate "%d/%m" oldDate then
                formatDate "%d/%m/%Y %I:%M %p" selectedDate
                    |> Date.fromString
                    |> Result.toMaybe
            else
                selectedDate
    in
        ( { model | selectedDate = newDate, calendarState = state }, Cmd.none )
```

The problem is with internationalization. The package is converting the string date using Date.fromString, which uses a native JavaScript parse that doesn't work with custom formats.

**Comment by abadi199** [comment]
I think the only way to solve this properly is to write a custom `Date.fromString` parser. I believe your workaround won't work when the user typed in the date in the input field directly without selected from the picker. Writing a date parser is something that I want to do, but I still need to find the time to do it. If someone else can write that, I will gladly use their package here. :smile_cat:

**Comment by rdourado** [comment]
I understand. My workaround is working for me, only in this specific case. It's not a definitive solution at all. I’ll try to write a custom parser myself. I'm still learning Elm, so it could be a good exercise. Furthermore, this issue is the only problem I'm having with your package. Thank you!

**Comment by abadi199** [comment]
I've published a date parser package (http://package.elm-lang.org/packages/abadi199/dateparser/latest) and also update the date picker package to give better support for i18n. Unfortunately, I had to make a breaking change in order to make the API for i18n better. Let me know if you have any more issue or question.
