### ISSUE TITLE
DateTimePicker.timePickerWithConfig, not working like expected

### ISSUE THREAD

**Issue by stoivo** [abadi199/datetimepicker#14]
it look like DateTimePicker.timePickerWithConfig is not working like expected 

I created an ellie app to demo it.
https://ellie-app.com/3gMHYPjXnnNa1/13

**Comment by avh4** [comment]
What is not working?  The ellie app linked to seems to work for me.

**Comment by stoivo** [comment]
My bad, change line 73
```
            | timePickerType = Digital
```

Then the selector doesn't work.

**Comment by abadi199** [comment]
This issue is fixed here https://github.com/abadi199/datetimepicker/commit/b36b02b06267bf2bd43bcdaca6d62d5e645b0380 and published as `3.0.2`
