### ISSUE TITLE
Timepicker should keep the date even if the time change

### ISSUE THREAD

**Issue by stoivo** [abadi199/datetimepicker#16]
https://ellie-app.com/3kJWSPnQWfHa1/5

**Comment by abadi199** [comment]
@stoivo Can you explain what's your use case here? I think when using time picker, the date part of the `Date` value should always be ignored. If you want to combine the time with some date value, I would recommend storing the date separately and then combine them later on. I wrote an example how you can do this: https://ellie-app.com/3mwzvrVg2wka1/1

**Comment by stoivo** [comment]
That seems to work. I used a different method of combining and since 1 .jan 1970 is not in summertime I got one hour off.  

I think I would have preferred to keep the date and only update the hours and minutes when selecting from the TimePicker.
