### ISSUE TITLE
Enable Travis-CI

### ISSUE THREAD

**Issue by avh4** [abadi199/datetimepicker#31]
@abadi199 I merged https://github.com/abadi199/datetimepicker/pull/28, which configures travis-ci for this repo, but for it to actually run, it needs to be turned on via travis.  Can you do one of the following:

  - (preferred) go to https://travis-ci.org/profile/abadi199 and enable it for this repo
  - or, give me admin access to this repo so I can enable travis
  - or, let me know a different CI provider that you'd prefer, and I can switch to that

**Comment by abadi199** [comment]
It doesn't seem like I can make you an admin for this repo. Maybe that's just for Organization? Regardless, I've turned on travis for this repo, so we should be good now. Let me know if you need anymore help from me.
