### ISSUE TITLE
Incompatible with latest elm-css

### ISSUE THREAD

**Issue by sporto** [abadi199/datetimepicker#38]
We would like to use this datepicker but we are using elm-css 12. This lib uses 8.
Please consider upgrading elm-css. Or maybe not using elm-css so there are no compatibility issues with elm-css in the apps.

**Comment by abadi199** [comment]
I'm actually thinking of splitting the `elm-css` code into separate package, so this package doesn't have direct dependency on `elm-css`. I'm probably gonna do some experiment with this idea soon.

**Comment by abadi199** [comment]
I just released version [`6.0.0`](http://package.elm-lang.org/packages/abadi199/datetimepicker/6.0.0) that doesn't have a direct dependency to `elm-css` anymore. Let me know if the new version will work for you or if you have any other concern. In a meantime, I will close this issue as solved.
