### ISSUE TITLE
Select year using the UI 

### ISSUE THREAD

**Issue by lisardo** [abadi199/datetimepicker#6]
In some cases, the user needs to select a specific year using the UI. Going month by month is inconvenient. Is there a way to do that?

It would look something like this:
![calendar](https://cloud.githubusercontent.com/assets/8375504/22338547/d05e356a-e3ce-11e6-95d1-e9f18310ecab.png)

**Comment by abadi199** [comment]
Good idea. Another option will be to have a fast forward/backward button to skip the year, like this:

![image](https://cloud.githubusercontent.com/assets/113792/22340012/9432166e-e3b1-11e6-87e7-d53b26d179aa.png)

Not sure which one will be more intuitive, the fast-forward button definitively uses less space.

**Comment by lisardo** [comment]
I like the fast forward button best. Is it some complicated change?

**Comment by abadi199** [comment]
I've implemented the fast forward button. It's published as `2.0.0`. Check it out, and let me know if you found any bugs. Thanks.

**Comment by lisardo** [comment]
@abadi199 Thank you so much! I would like start using this feature right away!

I'm just having an issue having with the layout, the arrows are in a weird position: 
<img width="243" alt="screen shot 2017-01-29 at 9 56 10 pm" src="https://cloud.githubusercontent.com/assets/8375504/22409262/02d31988-e66e-11e6-8e33-7474d7a959f0.png">

Any idea what is causing it?

**Comment by abadi199** [comment]
Yes, I forgot to update the `styles/styles.css`. I probably should setup a CI to automate that process. Sorry about that. Can you download the latest `styles/styles.css` file and let me know if it's working for you.

**Comment by lisardo** [comment]
I tried with the new css style and it worked perfectly. You are awesome!
