### ISSUE TITLE
Datepicker isn't updated when receiving new data

### ISSUE THREAD

**Issue by woylie** [abadi199/datetimepicker#7]
There's a bug when the date value is being updated. The date picker will still display the old value when opened for the first time after an update. See gist [here](https://gist.github.com/woylie/f99fbef86311c191b14ee3550fb0f8be).

**Comment by abadi199** [comment]
This is fixed with ton this PR https://github.com/abadi199/datetimepicker/pull/9
Deployed to `elm package` as `v2.0.2`
@woylie Can you double check if this issue has been resolved on the latest version?

**Comment by woylie** [comment]
@abadi199 It seems do work for the date now, but the problem still persists with the time.

**Comment by abadi199** [comment]
Ok, I think I got it this time. Can you try again with `v2.0.3`?

**Comment by woylie** [comment]
Yes, it works now. Thanks for the quick fix!
