### ISSUE TITLE
Feature request: 24 hour clock

### ISSUE THREAD

**Issue by woylie** [abadi199/datetimepicker#8]
It would be very nice if you could configure the DateTimePicker to use a 24h clock instead of a 12h clock.

**Comment by martindlarsson** [comment]
I second that! Goog work by the way

**Comment by eeue56** [comment]
@avh4 what do you think? In Europe, we usually don't use a digital clock with AM/PM, but rather with 24 hours. Making this configurable would be very handy. I know @stoivo is interested in making a PR but would like some guidance.

**Comment by avh4** [comment]
Yep, I'm in favor of adding the option.  I was doing some refactoring work a few months ago that only got partially finished.  I think that work invalidated the existing PR, but it did make the different picker panels more modular, so it shouldn't be hard to add the option once the refactoring is wrapped up.

**Comment by valberg** [comment]
Any news on this? Is there some low hanging fruit one could help with? Would be really neat to get this option in :smiley:

**Comment by woylie** [comment]
Stale.
